---
count: 8
default:
  restart: 0
  wait: 1
editor:
  files:
    base:
      - lib/App/TemplateCMD.pm
      - lib/App/TemplateCMD/Command.pm
      - lib/App/TemplateCMD/Command/Conf.pm
    main:
      - lib/App/TemplateCMD/Command/Print.pm
      - lib/App/TemplateCMD/Command/Build.pm
      - lib/App/TemplateCMD/Command/List.pm
    other:
      - lib/App/TemplateCMD/Command/Cat.pm
      - lib/App/TemplateCMD/Command/Describe.pm
      - lib/App/TemplateCMD/Command/Help.pm
    bin:
      - bin/templatecmd
name: tmplcmd
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    edit: base
  3:
    edit: main
  4:
    edit: other
  5:
    restart: 1
    edit: bin
